### ISSUE TITLE
How long will the Namerena update again?

### ISSUE THREAD

**Issue by ghost** [namerena/namerena.github.io#4]
If Namerena won't be update again, could you please release the sourse code to us? or maybe someone you beleive like Huajiww. thx

**Comment by ghost** [comment]
We are making mods inorder to improve Namerena's playability.(although we are not professional lol)

**Comment by rinick** [comment]
把邮件的内容直接在这里回复了吧。

新冠以来这边学校不开，所以白天带娃晚上上班，个人时间被挤压，想做的事情有很多。而名字竞技场的优先级很低。
做这个游戏的目的是让自己开心，所以即使一分钱赚不到之前也还是投入了大量时间，现在热情减退了自然花在上面的时间就少了。

热情减退的原因有几个：
-  玩家数量太少。虽然很感谢铁杆玩家们的支持，但是玩家人数才是对我的最大激励。
-  Dart语言现在成了Flutter专用语言。对普通网页的支持成了附带产品。这让我也不太想多在Dart项目上花时间
-  经常是打开项目之后想想要不要把以前防止反编译的东西再加回来，发现好像没必要，然后就直接关掉了:D
-  确实也没什么新想法，以后有什么想法的话还是会加上的。

 
另外游戏暂时不会开源。一旦机测变的过于容易，这个游戏的乐趣就会完全消失，所以开源是不可能的。官方测号器也只测属性，没有技能之类的功能。

**Comment by ghost** [comment]
> 把邮件的内容直接在这里回复了吧。
> 
> 新冠以来这边学校不开，所以白天带娃晚上上班，个人时间被挤压，想做的事情有很多。而名字竞技场的优先级很低。
> 做这个游戏的目的是让自己开心，所以即使一分钱赚不到之前也还是投入了大量时间，现在热情减退了自然花在上面的时间就少了。
> 
> 热情减退的原因有几个：
> 
> * 玩家数量太少。虽然很感谢铁杆玩家们的支持，但是玩家人数才是对我的最大激励。
> * Dart语言现在成了Flutter专用语言。对普通网页的支持成了附带产品。这让我也不太想多在Dart项目上花时间
> * 经常是打开项目之后想想要不要把以前防止反编译的东西再加回来，发现好像没必要，然后就直接关掉了:D
> * 确实也没什么新想法，以后有什么想法的话还是会加上的。
> 
> 另外游戏暂时不会开源。一旦机测变的过于容易，这个游戏的乐趣就会完全消失，所以开源是不可能的。所以官方测号器也只测属性，没有技能之类的功能。

谢谢！
